general:
  maxfev: 100000
  lags: 10
  results_dir: results
  input_dir: data_input
  use_smart_guess: true
  compare_models: true
  advanced_residuals: true

models:
  "1:1":
    initial_guess: [100, 100]
    bounds:
      lower: [0, 0]
      upper: [1e6, 1e6]

  "1:2":
    initial_guess: [100, 100, 100, 100]
    bounds:
      lower: [0, 0, -1e6, -1e6]
      upper: [1e6, 1e6, 1e6, 1e6]
  "2:1":
    initial_guess: [100, 100, 100, 100]
    bounds:
      lower: [0, 0, -1e6, -1e6]
      upper: [1e6, 1e6, 1e6, 1e6]

  "dimer":
    initial_guess: [100, 100, 100, 100]
    bounds:
      lower: [0, 0, -1e6, -1e6]
      upper: [1e6, 1e6, 1e6, 1e6]

  "multi":
    initial_guess: [100, 100, 100, 100, 100, 100]
    bounds:
      lower: [0, 0, 0, -1e6, -1e6, -1e6]
      upper: [1e6, 1e6, 1e6, 1e6, 1e6, 1e6]
